Repository RedHatOfficial/miq-RedHat-Satellite6, pull requests merged in 2018-10, with the labels that each got.

#76 update v5.9 dialogs to use get_locations_filtered_by_tags
  Dialogs/v5.9/Satellite_Provisioning.yml
  Dialogs/v5.9/Satellite_Provisioning_(Apache_HTTPD).yml
Labels: enhancement

#78 Satellite_Provisioning_(Apache_HTTPD).yml - change default location method
  Dialogs/v5.9/Satellite_Provisioning_(Apache_HTTPD).yml
Labels: bug

#80 set_custom_provision_task_options.rb - update custom_provision_type to custom_request_type
  Automate/RedHatConsulting_Satellite6/Service/Provisioning/StateMachines/Methods.class/__methods__/set_custom_provision_task_options.rb
Labels: bug

#81 register_satellite.rb - update for changes to miq-Utilities create_provision_requests
  Automate/RedHatConsulting_Satellite6/Integration/Satellite/Operations/Methods.class/__methods__/register_satellite.rb
Labels: API Breaking Change, enhancement
